[application]

# App (Project) Name
name = "dioxus-basic"

# Dioxus App Default Platform
# web, desktop, fullstack
default_platform = "web"

# `build` & `serve` dist path
out_dir = "dist"

# resource (assets) file folder
asset_dir = "assets"

[web.app]

# HTML title tag content
title = "dioxus-basic"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src"]

# include `assets` in web platform
[web.resource]

# CSS style file
#style = ["/tailwind.css"]


# Javascript code file
# "https://cdn.tailwindcss.com/3.4.5"
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
